---
title: "Assignment1"
---

Comparative Review - Breiman (2001) & Shmueli (2010)

Breiman (2001) puts forth the most common complaints that social scientists have, which is that in the bandwagon of using "exclusive statistical methods", statisticians have moved farther from strong theory building. The author highlights that the quality of the theory has been deduced and thus leading to incoherent research questions and results that are aimed to be associated on causality while they do not engender from good theoretic building. The increased focus on data rather than theory is the crux of his article in the light of data modeling and algorithmic models. Breiman(2001), expresses that data and theory are the key indicators of directing the modeling techniques.

Shmueli (2010) argues that there are three main types of modeling approaches, explanatory, predictive and descriptive. While descriptive is not more than a compressed summary of the data in general, explanatory models intend to test a causal relationship, however not just based on the data, but by fundamentally looking into the construct of the theory. Thus, it is the theory that dictates the strength of the potential causal association between the variables. While Shmueli (2010) explains this concept in depth building on the concepts of Breiman, and taking a step further in explaining the minor distinctions. Further Shmueli (2010) explains that predictive modelling is also important in the formation of causal theories. Adding to Breiman's (2001) take, Shmueli (2010) emphasizes that giving importance to all, data, theory and modeling technique is a promising step towards better causal theories and predictive analysis.
